apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mod-entities-links
  annotations:
    github.com/project-slug: psmagin/mod-entities-links
spec:
  type: service
  lifecycle: production
  owner: guests
